### ISSUE TITLE
Create class to obtain `packages` count

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#299] opened 2020-06-29 05:20 UTC
We need class to read `packages` attribute value of metadata `primary.xml` obtained from repository we are updating. Implementation can read first 5 lines of the given file with `BufferedReader` and try to get value of the attribute with the help of regular expression. Throw an exception if `packages` attribute was not found.
Put class into `meta` package and do not forget about test.

**Comment by 0crat** [comment] 2020-06-29 05:22
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0580059e-ceba-491e-980a-2a75bcaf1058, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 27' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [18139daa-2e64-4dc7-9186-afe1b6c58a81](https://www.0crat.com/footprint/CT2E6TK9B/18139daa-2e64-4dc7-9186-afe1b6c58a81), Type: "Job milestoned"

**Comment by olenagerasimova** [comment] 2020-06-29 05:22
@olegmoz could you please take a look? Let me know if smth is not clear

**Comment by 0crat** [comment] 2020-06-29 05:22
The job [#299](https://github.com/artipie/rpm-adapter/issues/299) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b200fb6c-bf18-42c0-8d0e-83c710b68aa0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by olegmoz** [comment] 2020-06-29 08:23
@olenagerasimova please give some clarification in this issue:
- Where this class is going to be used? Is it for some new features or is it about reducing code duplication?
- Is there is example of proper `primary.xml` in the project, to have as reference?
- Why do you suggest parsing XML as string via RegEx instead of proper tools for XML parsing?

**Comment by olenagerasimova** [comment] 2020-06-29 10:11
@olegmoz 
- this class will be used to optimize the update: if packages was added (via HTTP API put method for example) we can simply append corresponding information to metadata, set `packages` attribute to old `packages` value + amount of added packages and rewrite repomd.xml
- check `primary.xml.example` please
- it will work faster, regular expression will not be difficult, this tag can be met in the file only once - the task is not complex, I think we unlikely will face any mistakes/bugs here

**Comment by 0crat** [comment] 2020-06-30 15:02
Job [#299](https://github.com/artipie/rpm-adapter/issues/299) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment] 2020-06-30 15:02
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by olenagerasimova** [comment] 2020-06-30 15:13
@olegmoz please, check this [comment](https://github.com/artipie/rpm-adapter/pull/306#pullrequestreview-440006214), don't you mind reopening this issue and follow suggestions?

**Comment by olegmoz** [comment] 2020-06-30 15:50
@olenagerasimova sorry, missed the comment. Totally agree, will make required changes

**Comment by olegmoz** [comment] 2020-07-03 08:50
@olenagerasimova in comment to previous PR you have stated that `IllegalStateException` does not fit well for. Do you have some suggestion for better standard exception to use or you would like me to introduce special exception for this case?

**Comment by olenagerasimova** [comment] 2020-07-03 09:11
@olegmoz I think we can use `IllegalArgumentException`

**Closed** 2020-07-03 10:18 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-07-03 10:47
Job [#299](https://github.com/artipie/rpm-adapter/issues/299) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment] 2020-07-03 10:48
Job [#299](https://github.com/artipie/rpm-adapter/issues/299) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment] 2020-07-03 10:48
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment] 2020-07-03 11:54
@0crat quality good
